# Generated by Django 5.0.1 on 2024-01-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_students_aboutsponsor_editingindividual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editingindividual',
            name='status',
            field=models.CharField(choices=[('barchasi', 'Barchasi'), ('yangi', 'Yangi'), ('moderatsiyada', 'Moderatsiyada'), ('tasdiqlangan', 'Tasdiqlangan'), ('bekor_qilingan', 'Bekor qilingan')], max_length=100),
        ),
        migrations.AlterField(
            model_name='editinglegalentity',
            name='status',
            field=models.CharField(choices=[('barchasi', 'Barchasi'), ('yangi', 'Yangi'), ('moderatsiyada', 'Moderatsiyada'), ('tasdiqlangan', 'Tasdiqlangan'), ('bekor_qilingan', 'Bekor qilingan')], max_length=100),
        ),
        migrations.AlterField(
            model_name='sponsors',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sponsors',
            name='status',
            field=models.CharField(choices=[('barchasi', 'Barchasi'), ('yangi', 'Yangi'), ('moderatsiyada', 'Moderatsiyada'), ('tasdiqlangan', 'Tasdiqlangan'), ('bekor_qilingan', 'Bekor qilingan')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sponsorsfilter',
            name='application_status',
            field=models.CharField(choices=[('barchasi', 'Barchasi'), ('yangi', 'Yangi'), ('moderatsiyada', 'Moderatsiyada'), ('tasdiqlangan', 'Tasdiqlangan'), ('bekor_qilingan', 'Bekor qilingan')], default='barchasi', max_length=20),
        ),
    ]
