# Generated by Django 5.0.1 on 2024-01-28 20:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_sponsors_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField()),
                ('university_name', models.CharField(max_length=100)),
                ('contract_amount', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='studentfilter',
            name='university_name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='AboutStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.students')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AddSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name_of_sponsors', models.CharField(max_length=255, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sponsors'))),
                ('allocated_amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30000000)])),
                ('sponsors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sponsors')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AddStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField()),
                ('university_name', models.CharField(max_length=100)),
                ('type_of_student', models.CharField(choices=[('barchasi', 'Barchasi'), ('magistr', 'Magistr'), ('bakalavr', 'Bakalavr')], default='barchasi', max_length=100)),
                ('contract_amount', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.students')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EditSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sponsors'))),
                ('allocated_amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30000000)])),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sponsors')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
